### ISSUE TITLE
[suggestions] The dt prefix for datetimes seems redundant, as do the commas

### ISSUE THREAD

**Issue by mark-summerfield** [juddc/jxc#1]
Since your datetimes are basic ISO8601 format and contain _two_ hyphens, they are _always_ distinguishable from numbers (even suffixed ones like `5mm` or scientific `2023e-2`), so surely you could drop the dt prefix and just write datetimes raw, e.g. `2023-02-25`?

Also, the commas in lists seem to be redundant.

See for example [UXF](https://github.com/mark-summerfield/uxf).

**Comment by juddc** [comment]
I agree that removing the quotes around datetimes would be a readability improvement, but that would prevent them from being usable inside expressions. Eg. the expression `(2023-10-25)` parses as `[ Number(2023), Token(Minus), Number(10), Token(Minus), Number(25) ]`, but the expression `(dt"2023-10-25")` parses as `[DateTime(2023-10-25)]`.

I'm not sure what you mean about commas being redundant in lists - personally, I like the readability of having a visual separator character, especially because annotations can be a single identifier. You can get into visually ambiguous situations without that separator. For example: `[ abc 42px def nan null ]` - that's three values, but it's not particularly obvious.

Note that the commas are optional if you're using line breaks between values, so this is valid:
```
[
    abc 42px
    def nan
    null
]
```

**Comment by mark-summerfield** [comment]
I didn't realise you supported expressions. One solution that would avoid the quotes would be to use a leading char to indicate date/times, e.g., d2023-10-25.

As for lists, personally, I find commas a needless distraction. In JSON you must _not_ end a list with a comma; in Python you may or may not. In your example I don't understand why `abc 42px` is a single value; to me you eg should be written `['abc' 42px 'def' nan null]`; but clearly I've misunderstood.

**Comment by juddc** [comment]
For the datetime syntax, the current version allows the lexer to parse the whole value as a simple string, letting the parser handle the specific values inside the datetime. This has the effect of providing helpful error messages in case of a syntax mistake. I'm concerned that removing the quote characters would make some error messages very confusing, or worse, parse without any errors.

Using your syntax suggestion, `(dt2023-10-25 T 22:15)` and `(dt2023-10-25T22:15)` would both parse without errors. The first would parse to [`DateTime(2023-10-25)`, `Identifier(T)`, `Number(22)`, `Token(Colon)`, `Number(15)`], and the second would parse to [`DateTime(2023-10-25T22:15)`].

Don't get me wrong, I agree with you in principle - the less syntax noise the better. In this case though, there are a lot of benefits to having a delimiter of some kind on both sides of the value (both in readability and parsing), and I'm not convinced that the extra clarity is worth giving up those benefits.

For the value `abc 42px`, `abc` is the value's [annotation](https://jxc.juddnet.com/#annotations), which always starts with an identifier. There is generally a space between an annotation and its value, which is why you could end up with ambiguous situations if you didn't have some kind of separator between values. I should point out that JXC's separator syntax is fairly forgiving - trailing commas are optional (like Python), and as I mentioned before, you can also use a line break in place of a comma, so in practice, you only need to use commas in small lists, eg. `[ 0.2, -4.5, 10.7 ]`.

You may be interested in checking out JXC's [syntax diagrams](https://jxc.juddnet.com/syntax_diagrams.html).
